# Generated by Django 5.2.6 on 2025-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="phone",
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
